version = "3.1"
license = "LGPL-3"
date = "06 June 2017"
package = "luccme"
title = ""
url = "http://luccme.ccst.inpe.br/"
authors = "CCST - INPE"
contact = "luccme@inpe.br"
content = [[LuccME version 3.1 implementation.]]